"Release Version 1.2.18"

diff --git a/packaging/targets/trusty/debian/postinst b/packaging/targets/trusty/debian/postinst
--- a/packaging/targets/trusty/debian/postinst
+++ b/packaging/targets/trusty/debian/postinst
@@ -101,7 +101,25 @@ chown -R $USERNAME:$USERNAME $OI
 
 service openinfoman start || true
 
-sleep 10
+set +e
+i=0
+for (( ; i<10; ++i )); do
+   activation=$(service openinfoman status | grep running )
+   if [ -z "$activation" ]; then
+      i=10
+   else
+      false;
+   fi
+done
+set -e
+
+
+#if not running error out.
+service openinfoman status | grep running 
+
+
+#double check to see if server isup and running.  if not, fail install
+$WGET --no-check-certificate http://locahost:8984/CSD -O /dev/null  --timeout 15
 
 
 for SVS in ${SVSS[@]}
